/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const newVar = {
  "aws_project_region": "us-east-1",
  "aws_cognito_identity_pool_id": "us-east-1:b9ff8c7b-a261-444e-9851-1face990acab",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_I3MlFFxGS",
  "aws_user_pools_web_client_id": "3olf25j0gsrecdh0hsu52ct307",
  "oauth": {},
  "aws_cloud_logic_custom": [
    {
      "name": "apiffdceb0d",
      "endpoint": "https://924o0gon0i.execute-api.us-east-1.amazonaws.com/dev",
      "region": "us-east-1"
    }
  ]
}
const awsmobile = newVar;


export default awsmobile;
